[project]
name = "minimalkv"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.9"
azure-storage-blob = "*"
boto = "*"
boto3 = "*"
dulwich = "*"
fsspec = "*"
gcsfs = ">=2022.10.0"
s3fs = ">=2022.10.0"
psycopg2 = "*"
pyarrow = "*"
pymongo = "*"
pymysql = "*"
redis-py = "*"
sqlalchemy = "*"
uritools = "*"

[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"
wheel = "*"

[feature.test.dependencies]
docker-compose = "*"
pytest = ">=6"
pytest-cov = "*"
pytest-mock = "*"
pytest-xdist = "*"
mypy = "*"
types-mock = "*"
types-setuptools = "*"
types-redis = "*"
types-boto = "*"
boto3-stubs = "*"
mock = "*"
[feature.test.tasks]
test = "pytest"
test-coverage = "pytest --cov=minimalkv --cov-report=xml --cov-report=term-missing"

[feature.build.dependencies]
python-build = "*"
twine = "*"
[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."
check-wheel = "twine check dist/*"

[feature.lint.dependencies]
pre-commit = "*"
insert-license-header = "*"
docformatter = "*"
ruff = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"
pre-commit-update = "pre-commit autoupdate"

[feature.docs.dependencies]
sphinx = "*"
[feature.docs.tasks]
# Run task `postinstall` before building docs in docs environment
docs = "cd docs && make html"
readthedocs = "rm -rf $READTHEDOCS_OUTPUT/html && cp -r docs/_build/html $READTHEDOCS_OUTPUT/html"


[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
default = ["test"]
py39 = ["py39", "test"]
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
docs = ["docs"]
build = ["build"]
lint = { features = ["lint"], no-default-feature = true }
