name: pre-commit autoupdate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 4 * *"

defaults:
  run:
    shell: bash -el {0}

jobs:
  check_update:
    name: Check if newer version exists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        # We need to checkout with SSH here to have actions run on the PR.
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@92815284c57faa15cd896c4d5cfb2d59f32dc43d # v0.8.3
        with:
          environments: default lint
      - name: Update pre-commit hooks and run
        id: versions
        run: |
          pixi run pre-commit-update
          pixi run pre-commit-run --color=always --show-diff-on-failure || true

      - uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284
        with:
          commit-message: "Auto-update pre-commit hooks"
          title: "Auto-update pre-commit hooks"
          body: |
            New versions of the used pre-commit hooks were detected.
            This PR updates them to the latest and already ran `pre-commit run -a` for you to fix any changes in formatting.
          branch: pre-commit-autoupdate
          delete-branch: true
